### ISSUE TITLE
Versioning Issue with Husky 7.0.4

### ISSUE THREAD

**Issue by stephanfr** [skrtheboss/ts-async-semaphore#200]
**Describe the bug**
Installing ts-async-semaphore fails on the husky post-install step with husky 7.0.4 where there is a .git folder in the main project directory.

See issue for husky:  https://github.com/typicode/husky/issues/851

**To Reproduce**
Attempt to install ts-async-sempahore using

'npm install ts-async-semaphore'

when there is a .git folder in the main project directory.  Husky appears to get tripped up looking from the primary .git folder.

**Expected behavior**
Successful install

**Additional context**
Perhaps I am missing something but I have been using ts-async-semaphore *without* an associated git repo for my project (yet).  When I went to add some automated testing with jest and tried to use the jest watch capability, it complained about there not being a .git folder - so I used 'git init' to create a git context.  I ran into a different problem, so I blew away the node_modules folder and did a full install and that is when this problem bubbled up.  I am working around it for now by having no .git folder in my project and using the --watchAll option with jest.  I believe the moment I put my project into git, this issue will re-appear.

**Comment by skrtheboss** [comment]
@stephanfr thank you for reporting the issue. Has been fixed in version 3.0.3.
